name: argo-cd    # Irrelevant
apiVersion: v2      # Irrelevant once we can choose helm version in 7.0
version: 1.0.0      # Irrelevant
dependencies:       # Irrelevant
  - name: argo-cd
    version: 5.52.2
    repository: https://argoproj.github.io/argo-helm
